Numpy Introduction

In [2]:
#Buatlah array numpy yang berisikan nilai : 7,11,12,44,65,72
import numpy as np
array_numpy = np.array([7,11,12,44,65,72])
array_numpy

array([ 7, 11, 12, 44, 65, 72])

In [3]:
#Buatlah array numpy lainnya yang berisikan string: Koding Akademi, Pythin, Data Analyst, Programming
array_numpy_string = np.array(["Koding Akademi", "Python", "Data Analyst", "Programming"])
array_numpy_string

array(['Koding Akademi', 'Python', 'Data Analyst', 'Programming'],
      dtype='<U14')

In [4]:
#Tampilkan semua nilai dalam array tersebut satu-persatu dengan menggunakan looping
for i in array_numpy:
    print(i)

7
11
12
44
65
72


In [5]:
for a in array_numpy_string:
    print(a)

Koding Akademi
Python
Data Analyst
Programming


Numpy Arrays

In [8]:
#a. Tampilkan semua nilai dalam array (nilai 0-20)
a = np.arange(0,21,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
#b. Tampilkan nilai 5 - 12
a[5:13]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
#c. Tampilkan 3 nilai terakhir pada array
a[-3:]

array([18, 19, 20])

In [11]:
#d. Tampilkan nilai genap pada array
for i in a:
  if i %2 ==0:
    print(i)

0
2
4
6
8
10
12
14
16
18
20


Numpy Arrays Dimensions & Shapes

In [12]:
#Implementasikan matriks di atas ke dalam array Numpy 2 dan 3 dimensi
#Numpy 2 dimensi
dimensi_2 = np.array([
    [10, 20, 30],
    [5, 10, 20],
    [2, 4, 6]
])
dimensi_2

array([[10, 20, 30],
       [ 5, 10, 20],
       [ 2,  4,  6]])

In [13]:
dimensi_2_part2 = np.array([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])
dimensi_2_part2

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
dimensi_2_part3 = np.array([
    [20, 21, 22],
    [23, 24, 25],
    [26, 27, 28]
])
dimensi_2_part3

array([[20, 21, 22],
       [23, 24, 25],
       [26, 27, 28]])

In [15]:
dimensi_2_part4 = np.array([
    [30, 31, 32],
    [33, 34, 35],
    [36, 37, 38]
])
dimensi_2_part4

array([[30, 31, 32],
       [33, 34, 35],
       [36, 37, 38]])

In [16]:
#dimensi 3
array_3 = np.array([
    [
        [10, 20, 30],
        [5, 10, 20],
        [2, 4, 6],
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
    ],
    [
        [20, 21, 22],
        [23, 24, 25],
        [26, 27, 28],
    ],
    [
        [30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]
    ]
])
array_3

array([[[10, 20, 30],
        [ 5, 10, 20],
        [ 2,  4,  6]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

Numpy Arrays Indexing and Slicing of Matrices

In [17]:
#1. Buatlah data di atas ke dalam sebuah array numpy
import numpy as np
array_2_dimensi = np.array([
    ['Denis', 'Scratch', 8],
    ['Frank', 'Python', 18],
    ['Roger', 'Unity', 15]
])
array_2_dimensi

array([['Denis', 'Scratch', '8'],
       ['Frank', 'Python', '18'],
       ['Roger', 'Unity', '15']], dtype='<U11')

In [19]:
#2. Tampilkan masing-masing baris 1,2, dan 3 secara terpisah
array_2_dimensi [0]

array(['Frank', 'Python', '18'], dtype='<U11')

In [20]:
array_2_dimensi [1]

array(['Frank', 'Python', '18'], dtype='<U11')

In [21]:
array_2_dimensi[2]

array(['Roger', 'Unity', '15'], dtype='<U11')

In [22]:
#3. Tampilkan kolom pertama dan kedua
array_2_dimensi [:,:2]

array([['Denis', 'Scratch'],
       ['Frank', 'Python'],
       ['Roger', 'Unity']], dtype='<U11')

In [24]:
#4. Ubah data dengan nilai scratch menjadi roblox
array_2_dimensi[0][1] = 'Roblox'
array_2_dimensi

array([['Denis', 'Roblox', '8'],
       ['Frank', 'Python', '18'],
       ['Roger', 'Unity', '15']], dtype='<U11')

Numpy Operations

In [25]:
#1. Buatlah data di atas ke dalam sebuah array Numpy
import numpy as np
array_numpy_operation = np.array([
    [1, 'Januari', 4799],
    [2, 'Februari', 3154],
    [3, 'Maret', 4238],
    [4, 'April', 2929],
    [5, 'Mei', 1615]
])
array_numpy_operation

array([['1', 'Januari', '4799'],
       ['2', 'Februari', '3154'],
       ['3', 'Maret', '4238'],
       ['4', 'April', '2929'],
       ['5', 'Mei', '1615']], dtype='<U11')

In [26]:
#2. Jumlahkan semua nilai pada kolom ketiga
array_numpy_operation[:,2].astype(int).sum()

16735

In [27]:
#3. Carilah rata-rata dari kolom ketiga
array_numpy_operation[:,2].astype(int).mean()

3347.0

In [29]:
#4. Kalikanlah semua nilai pada kolom ketiga dengan 2
array_numpy_operation[:,2].astype(int) 
result = 2 * array_numpy_operation[:,2].astype(int) 
result

array([9598, 6308, 8476, 5858, 3230])

In [30]:
#5. Gantilah semua nilai pada kolom ketiga dengan nilai 5000
array_numpy_operation[:,2].astype(int)
array_numpy_operation[:,2] = 5000
array_numpy_operation

array([['1', 'Januari', '5000'],
       ['2', 'Februari', '5000'],
       ['3', 'Maret', '5000'],
       ['4', 'April', '5000'],
       ['5', 'Mei', '5000']], dtype='<U11')

Numpy Operations Boolean Arrays

In [31]:
#1. Buatlah 1 buah array Numpy berukuran 4 x 4 dengan menggunakan random nilai 100 sampai dengan 1000
A = np.random.randint(1000, size=(4,4))
A

array([[672, 195, 677, 813],
       [  8, 707, 300, 708],
       [289, 483, 548, 161],
       [484, 608, 434, 411]])

In [33]:
#2. Tampilkan elemen mana saja yang memiliki nilai > 500
data = np.where(A > 500, A,np.nan)
data

array([[672.,  nan, 677., 813.],
       [ nan, 707.,  nan, 708.],
       [ nan,  nan, 548.,  nan],
       [ nan, 608.,  nan,  nan]])

In [34]:
data[~np.isnan(data)]

array([672., 677., 813., 707., 708., 548., 608.])

In [36]:
#3. Tampilkan elemen mana saja yang memiliki nilai > 200 dan < 500
data = np.where((A > 200) & (A < 550), A,np.nan)
data[~np.isnan(data)]

array([300., 289., 483., 548., 484., 434., 411.])

NUMPY MINI PROJECT

In [37]:
#Program menerima 2 buah matriks 1 dimensi yang disimpan dalam masing-masing array Numpy
a = np.array([7,2,1,19,10,22,11,65])
a

array([ 7,  2,  1, 19, 10, 22, 11, 65])

In [38]:
b = np.array([17,12,11,29,16,25,19,4])
b

array([17, 12, 11, 29, 16, 25, 19,  4])

In [39]:
#2. Program memiliki return function dapat :
#a. Menjumlahkan kedua buah matriks
#b. Mencari sum, mean, dan standar deviasi dari masing-masing matriks
#3. Hasil akhir berupa penjumlahan kedua buah matriks, nilai sum, mean, dan standar deviasi dari masing-masing matriks

def matops(a,b):
  data = np.concatenate((a,b),axis=0)
  return data, a.sum(),b.sum(),a.mean(),b.mean(),a.std(),b.std()
matops(a,b)

(array([ 7,  2,  1, 19, 10, 22, 11, 65, 17, 12, 11, 29, 16, 25, 19,  4]),
 137,
 133,
 17.125,
 16.625,
 19.36128546868725,
 7.431983248097374)

In [46]:
c = a.sum() + b.sum()
c

270